<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2020

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.w3.org/1999/xhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="ns0 xs fn">
    <xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
    <xsl:template match="/">
        <doc>
            <xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'file:///C:/Users/CMA-MSI/dp1/src/assets/userdoc/mmst5_1/simpletoc.xsd'"/>
            <xsl:for-each select="ns0:html">
                <ul>
                    <xsl:for-each select="ns0:body/ns0:div/ns0:ul/ns0:li">
                        <xsl:variable name="var27_resultof_select_children" as="node()*" select="node()"/>
                        <xsl:variable name="var26_a" as="node()*" select="ns0:a"/>
                        <xsl:variable name="var25_test_resultof_any" as="xs:string*">
                            <xsl:choose>
                                <xsl:when test="fn:exists(($var27_resultof_select_children)[fn:boolean(self::text())])">
                                    <xsl:for-each select="($var27_resultof_select_children)[fn:boolean(self::text())]">
                                        <xsl:sequence select="fn:string(.)"/>
                                    </xsl:for-each>
                                </xsl:when>
                                <xsl:otherwise>
                                    <xsl:for-each select="($var26_a/node())[fn:boolean(self::text())]">
                                        <xsl:sequence select="fn:string(.)"/>
                                    </xsl:for-each>
                                </xsl:otherwise>
                            </xsl:choose>
                        </xsl:variable>
                        <li>
                            <xsl:if test="fn:exists($var25_test_resultof_any)">
                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var25_test_resultof_any return xs:string($x), ' '))"/>
                            </xsl:if>
                            <xsl:for-each select="$var26_a">
                                <xsl:attribute name="link" select="fn:string(@href)"/>
                            </xsl:for-each>
                            <xsl:for-each select="ns0:ul">
                                <ul>
                                    <xsl:for-each select="ns0:li">
                                        <xsl:variable name="var24_resultof_select_children" as="node()*" select="node()"/>
                                        <xsl:variable name="var23_a" as="node()*" select="ns0:a"/>
                                        <xsl:variable name="var22_test_resultof_any" as="xs:string*">
                                            <xsl:choose>
                                                <xsl:when test="fn:exists(($var24_resultof_select_children)[fn:boolean(self::text())])">
                                                    <xsl:for-each select="($var24_resultof_select_children)[fn:boolean(self::text())]">
                                                        <xsl:sequence select="fn:string(.)"/>
                                                    </xsl:for-each>
                                                </xsl:when>
                                                <xsl:otherwise>
                                                    <xsl:for-each select="($var23_a/node())[fn:boolean(self::text())]">
                                                        <xsl:sequence select="fn:string(.)"/>
                                                    </xsl:for-each>
                                                </xsl:otherwise>
                                            </xsl:choose>
                                        </xsl:variable>
                                        <li>
                                            <xsl:if test="fn:exists($var22_test_resultof_any)">
                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var22_test_resultof_any return xs:string($x), ' '))"/>
                                            </xsl:if>
                                            <xsl:for-each select="$var23_a">
                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                            </xsl:for-each>
                                            <xsl:for-each select="ns0:ul">
                                                <ul>
                                                    <xsl:for-each select="ns0:li">
                                                        <xsl:variable name="var21_resultof_select_children" as="node()*" select="node()"/>
                                                        <xsl:variable name="var20_a" as="node()*" select="ns0:a"/>
                                                        <xsl:variable name="var19_test_resultof_any" as="xs:string*">
                                                            <xsl:choose>
                                                                <xsl:when test="fn:exists(($var21_resultof_select_children)[fn:boolean(self::text())])">
                                                                    <xsl:for-each select="($var21_resultof_select_children)[fn:boolean(self::text())]">
                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                    </xsl:for-each>
                                                                </xsl:when>
                                                                <xsl:otherwise>
                                                                    <xsl:for-each select="($var20_a/node())[fn:boolean(self::text())]">
                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                    </xsl:for-each>
                                                                </xsl:otherwise>
                                                            </xsl:choose>
                                                        </xsl:variable>
                                                        <li>
                                                            <xsl:if test="fn:exists($var19_test_resultof_any)">
                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var19_test_resultof_any return xs:string($x), ' '))"/>
                                                            </xsl:if>
                                                            <xsl:for-each select="$var20_a">
                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                            </xsl:for-each>
                                                            <xsl:for-each select="ns0:ul">
                                                                <ul>
                                                                    <xsl:for-each select="ns0:li">
                                                                        <xsl:variable name="var18_resultof_select_children" as="node()*" select="node()"/>
                                                                        <xsl:variable name="var17_a" as="node()*" select="ns0:a"/>
                                                                        <xsl:variable name="var16_test_resultof_any" as="xs:string*">
                                                                            <xsl:choose>
                                                                                <xsl:when test="fn:exists(($var18_resultof_select_children)[fn:boolean(self::text())])">
                                                                                    <xsl:for-each select="($var18_resultof_select_children)[fn:boolean(self::text())]">
                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                    </xsl:for-each>
                                                                                </xsl:when>
                                                                                <xsl:otherwise>
                                                                                    <xsl:for-each select="($var17_a/node())[fn:boolean(self::text())]">
                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                    </xsl:for-each>
                                                                                </xsl:otherwise>
                                                                            </xsl:choose>
                                                                        </xsl:variable>
                                                                        <li>
                                                                            <xsl:if test="fn:exists($var16_test_resultof_any)">
                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var16_test_resultof_any return xs:string($x), ' '))"/>
                                                                            </xsl:if>
                                                                            <xsl:for-each select="$var17_a">
                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                            </xsl:for-each>
                                                                            <xsl:for-each select="ns0:ul">
                                                                                <ul>
                                                                                    <xsl:for-each select="ns0:li">
                                                                                        <xsl:variable name="var15_resultof_select_children" as="node()*" select="node()"/>
                                                                                        <xsl:variable name="var14_a" as="node()*" select="ns0:a"/>
                                                                                        <xsl:variable name="var13_test_resultof_any" as="xs:string*">
                                                                                            <xsl:choose>
                                                                                                <xsl:when test="fn:exists(($var15_resultof_select_children)[fn:boolean(self::text())])">
                                                                                                    <xsl:for-each select="($var15_resultof_select_children)[fn:boolean(self::text())]">
                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                    </xsl:for-each>
                                                                                                </xsl:when>
                                                                                                <xsl:otherwise>
                                                                                                    <xsl:for-each select="($var14_a/node())[fn:boolean(self::text())]">
                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                    </xsl:for-each>
                                                                                                </xsl:otherwise>
                                                                                            </xsl:choose>
                                                                                        </xsl:variable>
                                                                                        <li>
                                                                                            <xsl:if test="fn:exists($var13_test_resultof_any)">
                                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var13_test_resultof_any return xs:string($x), ' '))"/>
                                                                                            </xsl:if>
                                                                                            <xsl:for-each select="$var14_a">
                                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                                            </xsl:for-each>
                                                                                            <xsl:for-each select="ns0:ul">
                                                                                                <ul>
                                                                                                    <xsl:for-each select="ns0:li">
                                                                                                        <xsl:variable name="var12_resultof_select_children" as="node()*" select="node()"/>
                                                                                                        <xsl:variable name="var11_a" as="node()*" select="ns0:a"/>
                                                                                                        <xsl:variable name="var10_test_resultof_any" as="xs:string*">
                                                                                                            <xsl:choose>
                                                                                                                <xsl:when test="fn:exists(($var12_resultof_select_children)[fn:boolean(self::text())])">
                                                                                                                    <xsl:for-each select="($var12_resultof_select_children)[fn:boolean(self::text())]">
                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                    </xsl:for-each>
                                                                                                                </xsl:when>
                                                                                                                <xsl:otherwise>
                                                                                                                    <xsl:for-each select="($var11_a/node())[fn:boolean(self::text())]">
                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                    </xsl:for-each>
                                                                                                                </xsl:otherwise>
                                                                                                            </xsl:choose>
                                                                                                        </xsl:variable>
                                                                                                        <li>
                                                                                                            <xsl:if test="fn:exists($var10_test_resultof_any)">
                                                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var10_test_resultof_any return xs:string($x), ' '))"/>
                                                                                                            </xsl:if>
                                                                                                            <xsl:for-each select="$var11_a">
                                                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                                                            </xsl:for-each>
                                                                                                            <xsl:for-each select="ns0:ul">
                                                                                                                <ul>
                                                                                                                    <xsl:for-each select="ns0:li">
                                                                                                                        <xsl:variable name="var9_resultof_select_children" as="node()*" select="node()"/>
                                                                                                                        <xsl:variable name="var8_a" as="node()*" select="ns0:a"/>
                                                                                                                        <xsl:variable name="var7_test_resultof_any" as="xs:string*">
                                                                                                                            <xsl:choose>
                                                                                                                                <xsl:when test="fn:exists(($var9_resultof_select_children)[fn:boolean(self::text())])">
                                                                                                                                    <xsl:for-each select="($var9_resultof_select_children)[fn:boolean(self::text())]">
                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                    </xsl:for-each>
                                                                                                                                </xsl:when>
                                                                                                                                <xsl:otherwise>
                                                                                                                                    <xsl:for-each select="($var8_a/node())[fn:boolean(self::text())]">
                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                    </xsl:for-each>
                                                                                                                                </xsl:otherwise>
                                                                                                                            </xsl:choose>
                                                                                                                        </xsl:variable>
                                                                                                                        <li>
                                                                                                                            <xsl:if test="fn:exists($var7_test_resultof_any)">
                                                                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var7_test_resultof_any return xs:string($x), ' '))"/>
                                                                                                                            </xsl:if>
                                                                                                                            <xsl:for-each select="$var8_a">
                                                                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                                                                            </xsl:for-each>
                                                                                                                            <xsl:for-each select="ns0:ul">
                                                                                                                                <ul>
                                                                                                                                    <xsl:for-each select="ns0:li">
                                                                                                                                        <xsl:variable name="var6_resultof_select_children" as="node()*" select="node()"/>
                                                                                                                                        <xsl:variable name="var5_a" as="node()*" select="ns0:a"/>
                                                                                                                                        <xsl:variable name="var4_test_resultof_any" as="xs:string*">
                                                                                                                                            <xsl:choose>
                                                                                                                                                <xsl:when test="fn:exists(($var6_resultof_select_children)[fn:boolean(self::text())])">
                                                                                                                                                    <xsl:for-each select="($var6_resultof_select_children)[fn:boolean(self::text())]">
                                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                                    </xsl:for-each>
                                                                                                                                                </xsl:when>
                                                                                                                                                <xsl:otherwise>
                                                                                                                                                    <xsl:for-each select="($var5_a/node())[fn:boolean(self::text())]">
                                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                                    </xsl:for-each>
                                                                                                                                                </xsl:otherwise>
                                                                                                                                            </xsl:choose>
                                                                                                                                        </xsl:variable>
                                                                                                                                        <li>
                                                                                                                                            <xsl:if test="fn:exists($var4_test_resultof_any)">
                                                                                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var4_test_resultof_any return xs:string($x), ' '))"/>
                                                                                                                                            </xsl:if>
                                                                                                                                            <xsl:for-each select="$var5_a">
                                                                                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                                                                                            </xsl:for-each>
                                                                                                                                            <xsl:for-each select="ns0:ul">
                                                                                                                                                <ul>
                                                                                                                                                    <xsl:for-each select="ns0:li">
                                                                                                                                                        <xsl:variable name="var3_resultof_select_children" as="node()*" select="node()"/>
                                                                                                                                                        <xsl:variable name="var2_a" as="node()*" select="ns0:a"/>
                                                                                                                                                        <xsl:variable name="var1_test_resultof_any" as="xs:string*">
                                                                                                                                                            <xsl:choose>
                                                                                                                                                                <xsl:when test="fn:exists(($var3_resultof_select_children)[fn:boolean(self::text())])">
                                                                                                                                                                    <xsl:for-each select="($var3_resultof_select_children)[fn:boolean(self::text())]">
                                                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                                                    </xsl:for-each>
                                                                                                                                                                </xsl:when>
                                                                                                                                                                <xsl:otherwise>
                                                                                                                                                                    <xsl:for-each select="($var2_a/node())[fn:boolean(self::text())]">
                                                                                                                                                                        <xsl:sequence select="fn:string(.)"/>
                                                                                                                                                                    </xsl:for-each>
                                                                                                                                                                </xsl:otherwise>
                                                                                                                                                            </xsl:choose>
                                                                                                                                                        </xsl:variable>
                                                                                                                                                        <li>
                                                                                                                                                            <xsl:if test="fn:exists($var1_test_resultof_any)">
                                                                                                                                                                <xsl:attribute name="name" select="xs:string(fn:string-join(for $x in $var1_test_resultof_any return xs:string($x), ' '))"/>
                                                                                                                                                            </xsl:if>
                                                                                                                                                            <xsl:for-each select="$var2_a">
                                                                                                                                                                <xsl:attribute name="link" select="fn:string(@href)"/>
                                                                                                                                                            </xsl:for-each>
                                                                                                                                                            <xsl:for-each select="ns0:ul">
                                                                                                                                                                <ul>
                                                                                                                                                                    <xsl:sequence select="()"/>
                                                                                                                                                                </ul>
                                                                                                                                                            </xsl:for-each>
                                                                                                                                                        </li>
                                                                                                                                                    </xsl:for-each>
                                                                                                                                                </ul>
                                                                                                                                            </xsl:for-each>
                                                                                                                                        </li>
                                                                                                                                    </xsl:for-each>
                                                                                                                                </ul>
                                                                                                                            </xsl:for-each>
                                                                                                                        </li>
                                                                                                                    </xsl:for-each>
                                                                                                                </ul>
                                                                                                            </xsl:for-each>
                                                                                                        </li>
                                                                                                    </xsl:for-each>
                                                                                                </ul>
                                                                                            </xsl:for-each>
                                                                                        </li>
                                                                                    </xsl:for-each>
                                                                                </ul>
                                                                            </xsl:for-each>
                                                                        </li>
                                                                    </xsl:for-each>
                                                                </ul>
                                                            </xsl:for-each>
                                                        </li>
                                                    </xsl:for-each>
                                                </ul>
                                            </xsl:for-each>
                                        </li>
                                    </xsl:for-each>
                                </ul>
                            </xsl:for-each>
                        </li>
                    </xsl:for-each>
                </ul>
            </xsl:for-each>
        </doc>
    </xsl:template>
</xsl:stylesheet>
